# frozen_string_literal: true

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), 'scripts/autolinking')

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

$RNMapboxMapsImpl = 'mapbox'

platform :ios, '13.4'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
unless linkage.nil?
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! linkage: linkage.to_sym
end

target 'TerrasoLandPKS' do
  use_expo_modules!
  post_integrate do |installer|
    expo_patch_react_imports!(installer)
  rescue StandardError => e
    Pod::UI.warn e
  end
  pod 'MapboxMaps', '10.16.5'

  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    # An absolute path to your application root.
    app_path: "#{Pod::Config.instance.installation_root}/.."
  )

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      mac_catalyst_enabled: false
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CC'] = 'clang'
        config.build_settings['LD'] = 'clang'
        config.build_settings['CXX'] = 'clang++'
        config.build_settings['LDPLUSPLUS'] = 'clang++'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)',
                                                                   '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
      end
    end
  end
end
