name: localization

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  missing-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
          cache-dependency-path: |
            dev-client/package-lock.json

      - name: Install Node dependencies
        working-directory: ./dev-client
        run: npm ci

      - name: Run missing keys check
        working-directory: ./dev-client
        run: npm run localization-check-missing
