name: Test

on:
  merge_group:
  push:
    branches:
      - main
      - dependencies
  pull_request:
    branches:
      - main
      - dependencies
    types:
      - opened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".tool-versions"
          cache: "npm"
          cache-dependency-path: |
            dev-client/package-lock.json

      - name: Install Node dependencies
        working-directory: ./dev-client
        run: npm ci

      - name: Clear Jest cache
        working-directory: ./dev-client
        run: npm run test -- --clearCache

      - name: Test JavaScript
        working-directory: ./dev-client
        run: npm run test
